//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreationArtefact.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Facette générale de qualité</string>
  <string>Facette offensive</string>
  <string>Facette offensive: Attaque spéciale</string>
  <string>Facette défensive</string>
  <string>Facette de protection</string>
  <string>Facette de renforcement magique</string>
  <string>Facette de renforcement psychique</string>
  <string>Facette de renforcement de la convocation</string>
  <string>Facette de magie innée</string>
  <string>Facette d'augmentation</string>
  <string>Facette de maîtrise</string>
  <string>Facette ésotérique</string>
  <string>Facette ésotérique: Effet mystique</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Facette {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Facette"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>+5</string>
  <string>+10</string>
  <string>+15</string>
  <string>+20</string>
  <string>+25</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection BonusInc525 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BonusInc525"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Qualité moindre</string>
  <string>Qualité normale</string>
  <string>Qualité magistrale (+5)</string>
  <string>Qualité unique (+10)</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection BonusQualiteItem {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BonusQualiteItem"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>+5</string>
  <string>+10</string>
  <string>+15</string>
  <string>+20</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection BonusInc520 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BonusInc520"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>+10</string>
  <string>+20</string>
  <string>+30</string>
  <string>+40</string>
  <string>+50</string>
  <string>+60</string>
  <string>+80</string>
  <string>+100</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection BonusDegat {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BonusDegat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Enchantée</string>
  <string>Surnaturelle</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Enchantee {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Enchantee"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Froid</string>
  <string>Feu</string>
  <string>Électricité</string>
  <string>Lumière</string>
  <string>Obsurité</string>
  <string>Énergie</string>
  <string>Terre ou Eau ou Air</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Elementaire {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Elementaire"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Un type de race</string>
  <string>Un être en particulier</string>
  <string>Une condition</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Exterminateur {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Exterminateur"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Assaut</string>
  <string>Assaut majeur</string>
  <string>Force 8</string>
  <string>Force 10</string>
  <string>Force 12</string>
  <string>Force 15</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Assaut {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Assaut"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>10 Projectiles par jour</string>
  <string>25 Projectiles par jour</string>
  <string>100 Projectiles par jour</string>
  <string>Projectiles infinis</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Munition {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Munition"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>+10</string>
  <string>+20</string>
  <string>+30</string>
  <string>+40</string>
  <string>+50</string>
  <string>+60</string>
  <string>Critique automatique</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Critique {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Critique"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Lancement (actif)</string>
  <string>Lancement (passif)</string>
  <string>À vue</string>
  <string>À proximité</string>
  <string>Illimité</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Recuperation {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Recuperation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>-1 IP</string>
  <string>-2 IP</string>
  <string>-3 IP</string>
  <string>-4 IP</string>
  <string>-5 IP</string>
  <string>-6 IP</string>
  <string>-8 IP</string>
  <string>IP ignoré</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DestArmure {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DestArmure"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Précise</string>
  <string>Vorpal</string>
  <string>Transformation (Limité)</string>
  <string>Transformation (Complète)</string>
  <string>Contrôle des dégats</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AutreCompSpec {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AutreCompSpec"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Arme à l'attaque accrue</string>
  <string>Renforcement offensif</string>
  <string>Dégat accrus</string>
  <string>Arme enchantée</string>
  <string>Attaques élémentaires</string>
  <string>Exterminateur</string>
  <string>Assaut</string>
  <string>Munition illimitées</string>
  <string>Critique accru</string>
  <string>Récupération</string>
  <string>Destruction d'armure</string>
  <string>Autres compétence d'arme</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FacetteCombat {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FacetteCombat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Pierre</string>
  <string>Os commun</string>
  <string>Marbre</string>
  <string>Métal courant/Bois courant/Cuir courant</string>
  <string>Acier noir</string>
  <string>Ironwood</string>
  <string>Diamant</string>
  <string>Acier blanc</string>
  <string>Cuir draconique</string>
  <string>Illuminati[Anima]</string>
  <string>Perle noire</string>
  <string>Élektra[Anima]</string>
  <string>Bois de Ghestal[Anima]</string>
  <string>Malebolgia[Anima]</string>
  <string>Cold Iron[D&amp;D]</string>
  <string>Mythril[D&amp;D]</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Materiel {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Materiel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Entré des chiffres seulement.")]
        public string ErreurPresenceBase {
            get {
                return ((string)(this["ErreurPresenceBase"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Erreur")]
        public string Erreur {
            get {
                return ((string)(this["Erreur"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Qualité de combat</string>
  <string>Qualité générale</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FacetteQualite {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FacetteQualite"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Melee</string>
  <string>25m</string>
  <string>50m</string>
  <string>100m</string>
  <string> 250m</string>
  <string>1km</string>
  <string>Tout point visible</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DistanceAttSpec {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DistanceAttSpec"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>1/2 base de l'arme</string>
  <string>40</string>
  <string>60</string>
  <string>80</string>
  <string>100</string>
  <string>120</string>
  <string>150</string>
  <string>200</string>
  <string>250</string>
  <string>Base de l'arme</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DegatAttSpec {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DegatAttSpec"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Non</string>
  <string>1m radius</string>
  <string>3m radius</string>
  <string>5m radius</string>
  <string>10m radius</string>
  <string>25m radius</string>
  <string>100m radius</string>
  <string>250m radius</string>
  <string>500m radius</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ZoneAttSpec {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ZoneAttSpec"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Non</string>
  <string>80</string>
  <string>120</string>
  <string>180</string>
  <string>240</string>
  <string>320</string>
  <string>440</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CompOffAttSpec {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CompOffAttSpec"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Instant</string>
  <string>1</string>
  <string>2</string>
  <string>3</string>
  <string>4</string>
  <string>5</string>
  <string>6</string>
  <string>7</string>
  <string>8</string>
  <string>9</string>
  <string>10</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PrepAttSpec {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PrepAttSpec"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Ilimité</string>
  <string>1/jour</string>
  <string>3/jour</string>
  <string>5/jour</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection NBJourAttSpec {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["NBJourAttSpec"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>1</string>
  <string>2</string>
  <string>3</string>
  <string>4</string>
  <string>5</string>
  <string>6</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ArmureInnee {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ArmureInnee"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Physique</string>
  <string>Élémentaire</string>
  <string>Concentrée</string>
  <string>Complète</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ArmureInneeMod {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ArmureInneeMod"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Qualité de l'armure</string>
  <string>Armure innée</string>
  <string>Renforcement défensif</string>
  <string>Arme avec défense accrue</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FacetteDefensive {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FacetteDefensive"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>TRA</string>
  <string>CON</string>
  <string>PER</string>
  <string>CHA</string>
  <string>FRO</string>
  <string>ELE</string>
  <string>Physique</string>
  <string>Élémentaire</string>
  <string>Mystique</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TypeArmure {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TypeArmure"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Amplification de l'AMR</string>
  <string>Projection magique</string>
  <string>Réceptacle de Zéon</string>
  <string>Puissance ajouté</string>
  <string>Test de résistance mystique accrus</string>
  <string>Recharge magique</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FacetteMagique {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FacetteMagique"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Livre de Lumière</string>
  <string>Livre d'Obscurité</string>
  <string>Livre de Création</string>
  <string>Livre de Destruction</string>
  <string>Livre d'Air</string>
  <string>Livre d'Eau</string>
  <string>Livre de Feu</string>
  <string>Livre de Terre</string>
  <string>Livre d'Essence</string>
  <string>Livre d'Illusion</string>
  <string>Livre de Nécromancie</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection VoieDeMagie {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["VoieDeMagie"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>+5</string>
  <string>+10</string>
  <string>+15</string>
  <string>+20</string>
  <string>+25</string>
  <string>+30</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection BonusInc530 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BonusInc530"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>50</string>
  <string>100</string>
  <string>200</string>
  <string>250</string>
  <string>500</string>
  <string>750</string>
  <string>1000</string>
  <string>1500</string>
  <string>2000</string>
  <string>3000</string>
  <string>5000</string>
  <string>10000</string>
  <string>Illimité</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ReceptZeon {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ReceptZeon"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>+10 points de Zéon</string>
  <string>+20 points de Zéon</string>
  <string>+30 points de Zéon</string>
  <string>+40 points de Zéon</string>
  <string>Degré supérieur</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PuisAjoute {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PuisAjoute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>+10</string>
  <string>+15</string>
  <string>+20</string>
  <string>+25</string>
  <string>+30</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection BonusInc510to30 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BonusInc510to30"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>+10</string>
  <string>+20</string>
  <string>+30</string>
  <string>+40</string>
  <string>+50</string>
  <string>+60</string>
  <string>Double</string>
  <string>Triple</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection RegenMag {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RegenMag"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Talent</string>
  <string>Projection psychique</string>
  <string>Test de résistance psychique accrus</string>
  <string>Amélioration du maintien des pouvoirs</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FacettePsychique {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FacettePsychique"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>+10</string>
  <string>+20</string>
  <string>+30</string>
  <string>+40</string>
  <string>+50</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection BonusInc1010to50 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BonusInc1010to50"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Télépathie</string>
  <string>Télékinésie</string>
  <string>Pyrokinésie</string>
  <string>Cryokinésie</string>
  <string>Augmentation physique</string>
  <string>Énergie</string>
  <string>Sensation</string>
  <string>Télémétrie</string>
  <string>Causalité</string>
  <string>Électromagnétisme</string>
  <string>Téléportation</string>
  <string>Lumière</string>
  <string>Hypersensibilité</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DiscplinePsy {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DiscplinePsy"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Présence accrue</string>
  <string>Lien économe</string>
  <string>Convocation accrue</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FacetteConvocation {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FacetteConvocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>+10</string>
  <string>+20</string>
  <string>+30</string>
  <string>+50</string>
  <string>+75</string>
  <string>+100</string>
  <string>+150</string>
  <string>+200</string>
  <string>+250</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Presence {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Presence"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>-1 niveau</string>
  <string>-2 niveaux</string>
  <string>-3 niveaux</string>
  <string>-4 niveaux</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LienEconome {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LienEconome"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>+5</string>
  <string>+10</string>
  <string>+15</string>
  <string>+20</string>
  <string>+25</string>
  <string>+30</string>
  <string>+40</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ConvoAccrue {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ConvoAccrue"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Aucun</string>
  <string>Air</string>
  <string>Terre</string>
  <string>Feu</string>
  <string>Eau</string>
  <string>Noirceur[Anima]</string>
  <string>Lumière[Anima]</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ElementLie {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ElementLie"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Convoquer</string>
  <string>Dominer</string>
  <string>Lier</string>
  <string>Révoquer</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ConvoLie {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ConvoLie"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Immunité</string>
  <string>Immunité magique</string>
  <string>Immunité psychique</string>
  <string>Immunité élémentaire</string>
  <string>Réduction des dégats</string>
  <string>Seuil d'invulnérabilité</string>
  <string>Amélioration des résistances</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FacetteProtection {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FacetteProtection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Dégats réduits de moitié</string>
  <string>Dégats physiques</string>
  <string>Dégats mystique réduits de moitié</string>
  <string>N'importe quelle Présence</string>
  <string>Présence supérieur à 80</string>
  <string>Présence supérieur à 120</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Immunite {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Immunite"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Zéon 40</string>
  <string>Zéon 80</string>
  <string>Zéon 120</string>
  <string>Zéon 180</string>
  <string>Zéon 250</string>
  <string>Zéon 350</string>
  <string>Zéon 500</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ImmuniteMag {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ImmuniteMag"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Test de Talent 80</string>
  <string>Test de Talent 120</string>
  <string>Test de Talent 140</string>
  <string>Test de Talent 180</string>
  <string>Test de Talent 240</string>
  <string>Test de Talent 280</string>
  <string>Test de Talent 320</string>
  <string>Matrices complètes</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ImmunitePsy {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ImmunitePsy"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>2 intensités</string>
  <string>4 intensités</string>
  <string>6 intensités</string>
  <string>10 intensités</string>
  <string>20 intensités</string>
  <string>Immunité totale</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ImmuniteElem {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ImmuniteElem"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Air</string>
  <string>Terre</string>
  <string>Feu</string>
  <string>Eau</string>
  <string>Noirceur[Anima]</string>
  <string>Lumière[Anima]</string>
  <string>Éléments naturels</string>
  <string>Tous les éléments[Anima]</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TypeImmuniteElem {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TypeImmuniteElem"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>-10</string>
  <string>-20</string>
  <string>-30</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ReducDegats {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ReducDegats"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>40</string>
  <string>60</string>
  <string>80</string>
  <string>100</string>
  <string>120</string>
  <string>150</string>
  <string>180</string>
  <string>200</string>
  <string>250</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Invulnerabilite {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Invulnerabilite"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>+10</string>
  <string>+20</string>
  <string>+30</string>
  <string>+40</string>
  <string>+50</string>
  <string>+80</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AmelioRes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AmelioRes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>RPhy</string>
  <string>RPoi</string>
  <string>RMal</string>
  <string>RMys</string>
  <string>RPsy</string>
  <string>De type physique</string>
  <string>De type mystique</string>
  <string>Toutes les résistances</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TypeAmelioRes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TypeAmelioRes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Sort automatique</string>
  <string>Lanceur de sorts</string>
  <string>Compétence de lancement</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FacetteMagieInnee {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FacetteMagieInnee"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>80</string>
  <string>120</string>
  <string>160</string>
  <string>200</string>
  <string>240</string>
  <string>280</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CompLancement {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CompLancement"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Sans le Don</string>
  <string>AMR double</string>
  <string>Inné</string>
  <string>Coût réduit  de moitié</string>
  <string>Autonomie d'énergie</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ModLanceurSort {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ModLanceurSort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Initiative</string>
  <string>Régénération</string>
  <string>Augmentation du déplacement</string>
  <string>Augmentation des compétences secondaires</string>
  <string>Augmentation des caractéristiques</string>
  <string>Substitution de caractéristique</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FacetteAugmentation {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FacetteAugmentation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Régénération 4</string>
  <string>Régénération 8</string>
  <string>Régénération 12</string>
  <string>Régénération 14</string>
  <string>Régénération 16</string>
  <string>Régénération +1</string>
  <string>Régénération +2</string>
  <string>Régénération +4</string>
  <string>Régénération +6</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Regeneration {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Regeneration"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>+1</string>
  <string>+2</string>
  <string>+3</string>
  <string>+4</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Mouvement {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Mouvement"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>+10</string>
  <string>+25</string>
  <string>+50</string>
  <string>+75</string>
  <string>+100</string>
  <string>+10 Champ complet</string>
  <string>+20 Champ complet</string>
  <string>+30 Champ complet</string>
  <string>+40 Champ complet</string>
  <string>+50 Champ complet</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AugCompSec {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AugCompSec"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>+1</string>
  <string>+2</string>
  <string>+3</string>
  <string>+4</string>
  <string>+5</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AugCarac {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AugCarac"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>8</string>
  <string>10</string>
  <string>11</string>
  <string>12</string>
  <string>14</string>
  <string>15</string>
  <string>16</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SubstiCarac {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SubstiCarac"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Athlétique</string>
  <string>Sociale</string>
  <string>Sensorielle</string>
  <string>Intellectuelle</string>
  <string>Vitale</string>
  <string>Clandestine</string>
  <string>Créative</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ChampSec {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ChampSec"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Renforcement d'accumulation du Ki</string>
  <string>Technique spéciale</string>
  <string>Réserve de Ki</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FacetteMaitrise {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FacetteMaitrise"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Force</string>
  <string>Constitution</string>
  <string>Agilité</string>
  <string>Dextérité</string>
  <string>Pouvoir</string>
  <string>Volonté</string>
  <string>Caractéristiques physiques</string>
  <string>Caractéristiques d'habilité</string>
  <string>Caractéristiques animiques</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LienAccumulation {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LienAccumulation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>+1</string>
  <string>+2</string>
  <string>+3</string>
  <string>+4</string>
  <string>+5</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AccumulationKi {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AccumulationKi"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Niveau 1</string>
  <string>Niveau 2</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TechKi {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TechKi"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>12</string>
  <string>24</string>
  <string>36</string>
  <string>48</string>
  <string>60</string>
  <string>120</string>
  <string>180</string>
  <string>240</string>
  <string>300</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ReserveKi {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ReserveKi"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Prothèse</string>
  <string>Altération du destin</string>
  <string>Dissimulation améliorée</string>
  <string>Moyen spéciaux de vision</string>
  <string>Effets mineurs</string>
  <string>Ego</string>
  <string>Créateur de portail</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FacetteEsoterique {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FacetteEsoterique"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Membre inférieur</string>
  <string>Membre parfait</string>
  <string>Membre supérieur</string>
  <string>Organe sensitif inférieur</string>
  <string>Organe sensitif parfait</string>
  <string>Organe sensitif supérieur</string>
  <string>Organe interne inférieur</string>
  <string>Organe interne parfait</string>
  <string>Organe interne supérieur</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Prothese {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Prothese"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Réduction des maladresses</string>
  <string>Amélioration critique</string>
  <string>Doubles</string>
  <string>Altération existentielle</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Destin {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Destin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Absurde</string>
  <string>Quasiment impossible</string>
  <string>Impossible</string>
  <string>Surhumain</string>
  <string>Zen</string>
  <string>Indétectable</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Dissimulation {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Dissimulation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir</string>
  <string>Vision nocturne</string>
  <string>Vision nocturne totale</string>
  <string>Voir la magie</string>
  <string>Voir les matrices</string>
  <string>Voir les esprits</string>
  <string>Voir le surnaturel</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Vision {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Vision"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Ego simple</string>
  <string>Ego complexe</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Ego {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Ego"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Porte vers la veille[Anima]/Plan élémentaire[D&amp;D] (Voile faibe)</string>
  <string>Porte vers la veille[Anima]/Plan[D&amp;D]</string>
  <string>Portail (lieu déterminé)</string>
  <string>Portail fixe</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Portal {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Portal"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Peur</string>
  <string>Terreur</string>
  <string>Douleur</string>
  <string>Douleur extrême</string>
  <string>Faiblesse</string>
  <string>Paralysie partielle</string>
  <string>Paralysie totale</string>
  <string>Colère</string>
  <string>Cécité</string>
  <string>Surdité</string>
  <string>Mutisme</string>
  <string>Fascination</string>
  <string>Dégâts simples</string>
  <string>Dégâts doubles</string>
  <string>Inconscience</string>
  <string>Domination</string>
  <string>Mort</string>
  <string>Folie</string>
  <string>Vieillesse</string>
  <string>Malus à toute action</string>
  <string>Destruction de caractéristiques</string>
  <string>Drain (moitié)</string>
  <string>Drain (comlet)</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection EffetMystique {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EffetMystique"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>RMys 40</string>
  <string>RMys 80</string>
  <string>RMys 100</string>
  <string>RMys 120</string>
  <string>RMys 140</string>
  <string>RMys 180</string>
  <string>RMys 200</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ResistanceEffet {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ResistanceEffet"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Par les dégâts</string>
  <string>Par le contact</string>
  <string>Par le son</string>
  <string>Par la vue</string>
  <string>Par l'odeur</string>
  <string>Zone (5 mètres)</string>
  <string>Zone (10 mètres)</string>
  <string>Zone (25 mètres)</string>
  <string>Zone (50 mètres)</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ConditionEffet {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ConditionEffet"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Choisir...</string>
  <string>Occultation</string>
  <string>Transfert</string>
  <string>Maestria</string>
  <string>Indestructibilité</string>
  <string>Autodestruction</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection EffetMineur {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EffetMineur"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Illimité</string>
  <string>5 fois par jour</string>
  <string>3 fois par jour</string>
  <string>1 fois par jour</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection NBUtilsPortal {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["NBUtilsPortal"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\")]
        public string RepertoireInit {
            get {
                return ((string)(this["RepertoireInit"]));
            }
            set {
                this["RepertoireInit"] = value;
            }
        }
    }
}
